### ISSUE TITLE
No module named contactmatricesworld_function.r

### ISSUE THREAD

**Issue by Elijah-pycode** [kieshaprem/synthetic-contact-matrices#1]
Please，I am facing issues that cannot find the module "codes/contactmatricesworld_function.r", while it is mentioned in the module "generate_synthetic_matrices/codes/pop_getWBindicators.r", as "source('codes/contactmatricesworld_function.r')" .

**Comment by kieshaprem** [comment]
Thanks for raising that issue. We have updated the codes.

Alternatively, you may replace
`source('codes/contactmatricesworld_function.r')`
with 
`source('codes/functions_processContactmatrices.r')`
